print("="*80)
print("FINAL MODEL EVALUATION SUMMARY")
print("="*80)
print(f"\n🎯 MODEL: Random Forest Regressor")
print(f"   Training Samples: {len(split_X_train)} | Test Samples: {len(split_X_test)}")
print(f"   Features: {len(best_model_metrics['features'])}")

print(f"\n📊 PRIMARY METRIC - MAPE (Mean Absolute Percentage Error):")
print(f"   ├─ Training MAPE: {eval_train_mape:.2f}%")
print(f"   └─ Test MAPE: {eval_test_mape:.2f}% ⭐")
print(f"      → On average, predictions deviate by ~{eval_test_mape:.2f}% from actual salaries")

print(f"\n📈 ADDITIONAL METRICS:")
print(f"   ├─ MAE (Mean Absolute Error)")
print(f"   │  ├─ Training: ${rf_train_mae:,.2f}")
print(f"   │  └─ Test: ${rf_test_mae:,.2f}")
print(f"   │")
print(f"   ├─ RMSE (Root Mean Squared Error)")
print(f"   │  ├─ Training: ${rf_train_rmse:,.2f}")
print(f"   │  └─ Test: ${rf_test_rmse:,.2f}")
print(f"   │")
print(f"   └─ R² Score (Coefficient of Determination)")
print(f"      ├─ Training: {rf_train_r2:.4f}")
print(f"      └─ Test: {rf_test_r2:.4f}")
print(f"         → Model explains {rf_test_r2*100:.2f}% of salary variance")

print(f"\n✅ MODEL PERFORMANCE ASSESSMENT:")
print(f"   • Random Forest is the best performing model (vs Linear Reg & Gradient Boosting)")
print(f"   • Test R² of {rf_test_r2:.4f} shows moderate predictive power")
print(f"   • MAPE of {eval_test_mape:.2f}% indicates percentage-based prediction error")
print(f"   • MAE of ${rf_test_mae:,.0f} shows typical absolute error magnitude")
print(f"   • Model ready for salary predictions on similar data")

print("\n" + "="*80)
print("✓ EVALUATION COMPLETE - All metrics calculated and visualizations generated")
print("="*80)